"""empty message

Revision ID: afbe58c9d382
Revises: 0cdf173a76b7
Create Date: 2019-04-18 14:12:50.867769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afbe58c9d382'
down_revision = '0cdf173a76b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elastic_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_id', sa.String(length=40), nullable=True),
    sa.Column('password', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('elastic_users')
    # ### end Alembic commands ###
